language: node_js
node_js:
- '1.5'
- '0.12'
- '0.10'
services:
- redis-server
notifications:
  hipchat:
    rooms:
      secure: FZUOHDpKBfr/54WKT2epXAiRW5B6Tgpg9Bsfvuz5Mg1AOEkdE8kYBjeP9oUegJCUlsXvtO9VE3tf2fdI3hMKNc+yLXgvYDvsmjhTiVXk23of17zH2FTjFdbO/vm4SBSnh6wdg2qHGB8s2Y08uKADojRX6Vnznoy4d+k+nRaZrNA=
